# ==============================================================================
# Title: Enterprise Syslog Network Anomaly Detector via Adaptive ML (ETS)
# Author: Matutuzela Jabulani Ndlovu (Rex-OG-Kush)
# Description: Adaptive ML pipeline utilizing time-series state-space modeling
#              to isolate network intrusion anomalies across cyclical trends.
# ==============================================================================

# 1. ENVIRONMENT INITIALIZATION
r_pkgs <- c("tidyverse", "tsibble", "fable", "distributional")
if (any(!map_lgl(r_pkgs, require, character.only = TRUE))) {
  install.packages(r_pkgs, repos = "https://r-project.org")
  walk(r_pkgs, library, character.only = TRUE)
}

set.seed(930925)

# 2. SYNTHETIC ENTERPRISE SYSLOG GENERATOR WITH DIURNAL CYCLES
generate_syslog_telemetry <- function(days = 7) {
  cat("[*] Generating baseline enterprise network telemetry with cyclical variations...\n")
  
  total_intervals <- days * 24 * 60 
  timeline <- seq(from = Sys.time() - (days * 86400), length.out = total_intervals, by = "1 min")
  
  # Inject daily cyclical pattern (higher traffic mid-day, lower at night)
  hour_vectors <- as.numeric(format(timeline, "%H"))
  diurnal_lambda <- 45 + 25 * sin((hour_vectors - 6) * pi / 12)
  base_traffic <- rpois(total_intervals, lambda = diurnal_lambda) 
  
  # Inject threat anomalies (DDoS & Low-and-Slow probing escalations)
  anomaly_indices <- c(2500, 4320, 7100, 9500)
  base_traffic[anomaly_indices] <- base_traffic[anomaly_indices] + c(450, 620, 890, 510)
  
  telemetry_dataframe <- tibble(
    timestamp = timeline,
    device_id = sample(c("JHB-CORE-RT01", "CPT-EDGE-SW02", "DBN-FW-DMZ01"), total_intervals, replace = TRUE),
    inbound_connections_per_min = base_traffic,
    syslog_status = sample(c("INFO-200", "NOTICE-205", "WARN-401"), total_intervals, replace = TRUE, prob = c(0.92, 0.06, 0.02))
  )
  
  telemetry_dataframe$syslog_status[anomaly_indices] <- "CRIT-500" 
  return(telemetry_dataframe)
}

# 3. ADAPTIVE MACHINE LEARNING PIPELINE (ETS MODELLING)
execute_anomaly_detection <- function(data) {
  cat("[*] Transforming tracking data to Tsibble and fitting ETS model arrays...\n")
  
  # Aggregate raw 1-minute data into 15-minute buckets for computational efficiency
  ts_data <- data %>%
    mutate(time_bucket = floor_date(timestamp, "15 mins")) %>%
    group_by(time_bucket) %>%
    summarise(
      inbound_connections = sum(inbound_connections_per_min),
      contains_crit_flag = any(syslog_status == "CRIT-500"),
      targeted_device = first(device_id)
    ) %>%
    as_tsibble(index = time_bucket)
  
  # Fit an automated Error, Trend, Seasonal (ETS) state-space model framework
  fit <- ts_data %>%
    model(ets_model = ETS(inbound_connections))
  
  # Extract fitted values and compute dynamic 99% Upper Prediction Boundaries
  modeled_residuals <- augment(fit)
  
  analyzed_telemetry <- modeled_residuals %>%
    mutate(
      fitted_mean = .fitted,
      dynamic_ucl = .fitted + (2.576 * sd(.innov, na.rm = TRUE)),
      is_anomaly = inbound_connections > dynamic_ucl,
      operational_alert_level = case_when(
        is_anomaly & contains_crit_flag ~ "EMERGENCY: ADAPTIVE ML THREAT DETECTION",
        is_anomaly ~ "WARNING: TREND OUTLIER DETECTED",
        TRUE ~ "STATUS-NORMAL"
      ),
      targeted_device = ts_data$targeted_device
    )
  
  return(analyzed_telemetry)
}

# 4. EXECUTION RUNTIME & PIPELINE VERIFICATION
raw_network_data <- generate_syslog_telemetry(days = 7)
analyzed_results <- execute_anomaly_detection(raw_network_data)

isolated_threats <- analyzed_results %>% 
  filter(is_anomaly == TRUE)

# 5. CLOSED-LOOP ACTIVE DEFENSE MITIGATION & DATA EXPORT
if (nrow(isolated_threats) > 0) {
  cat("[*] Threat anomalies verified. Generating logs and adaptive visualization mappings...\n")
  write_csv(as_tibble(isolated_threats), "isolated_threats_report.csv")
  
  # ACTIVE DEFENSE ENGINE: Generate a synthetic dynamic firewall drop matrix script
  # In production, these IPs would be extracted directly from your parsed raw logs.
  synthetic_attacker_ips <- c("192.168.42.11", "10.0.4.89", "172.16.22.4", "192.168.88.21")
  
  bash_script_lines <- c(
    "#!/bin/bash",
    "# ==============================================================================",
    "# AUTOMATED FIREWALL BLOCKLIST MANIFEST GENERATED BY SYSTEM DETECTION PIPELINE",
    paste("# Generated Execution Time:", Sys.time()),
    "# ==============================================================================",
    ""
  )
  
  for (ip in synthetic_attacker_ips) {
    bash_script_lines <- c(bash_script_lines, paste0("sudo iptables -A INPUT -s ", ip, " -j DROP"))
    bash_script_lines <- c(bash_script_lines, paste0("echo '[!] Firewall rule deployed: Dropping traffic from ", ip, "'"))
  }
  
  writeLines(bash_script_lines, "blocklist_manifest.sh")
  cat("[+] Automated mitigation firewall asset created: blocklist_manifest.sh\n")
  
  # Build metadata summary metrics text file for Discord consumption
  critical_metric <- max(isolated_threats$inbound_connections)
  target_device <- isolated_threats$targeted_device[1]
  
  summary_lines <- c(
    paste0("ALERT_STATUS=CRITICAL"),
    paste0("METRIC_PEAK=", critical_metric),
    paste0("TARGET_NODE=", target_device)
  )
  writeLines(summary_lines, "threat_summary.env")
  
  # Structural implementation of Dashboard Dark UI Aesthetics
  threat_plot <- ggplot(analyzed_results, aes(x = time_bucket, y = inbound_connections)) +
    geom_line(color = "#3a4f66", alpha = 0.6, linewidth = 0.5) +
    geom_line(aes(y = dynamic_ucl), color = "#ff4d4d", linetype = "dashed", linewidth = 0.8) +
    geom_point(data = isolated_threats, aes(color = operational_alert_level), size = 3.5, shape = 18) +
    scale_color_manual(values = c("EMERGENCY: ADAPTIVE ML THREAT DETECTION" = "#e74c3c", 
                                  "WARNING: TREND OUTLIER DETECTED" = "#f39c12")) +
    labs(
      title = "SIEM ENTERPRISE TELEMETRY ADAPTIVE ML MAP",
      subtitle = "Dynamic Exponential Smoothing (ETS) Time-Series Control Array",
      x = "Chronological Tracking Framework Log Timeline",
      y = "Aggregated Connection Volumes (15 Min Buckets)",
      color = "System Core Incident Categorization"
    ) +
    theme_minimal(base_family = "sans") +
    theme(
      plot.background = element_rect(fill = "#0f172a", color = NA),
      panel.background = element_rect(fill = "#0f172a", color = NA),
      panel.grid.major = element_line(color = "#1e293b", linewidth = 0.5),
      panel.grid.minor = element_blank(),
      text = element_text(color = "#94a3b8"),
      plot.title = element_text(color = "#f8fafc", face = "bold", size = 14),
      plot.subtitle = element_text(color = "#38bdf8", size = 10, margin = margin(b = 15)),
      axis.text = element_text(color = "#64748b"),
      legend.position = "bottom",
      legend.background = element_rect(fill = "#1e293b", color = NA),
      legend.text = element_text(color = "#e2e8f0"),
      legend.key = element_blank()
    )

  ggsave("network_threat_analysis.png", plot = threat_plot, width = 11, height = 6.5, dpi = 300)
  
} else {
  cat("[-] Complete dataset operations nominal.\n")
  write_csv(tibble(status="System Nominal - Zero Boundary Control Deviations Found"), "isolated_threats_report.csv")
  writeLines(c("ALERT_STATUS=NOMINAL"), "threat_summary.env")
}
